version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    environment:
      - NODE_ENV=development
    command: sleep infinity
    ports:
      - "3000:3000"  # Backend port
      - "5173:5173"  # Frontend port
    networks:
      - libtrack-network

volumes:
  postgres-data:

networks:
  libtrack-network:
    driver: bridge 
